### ISSUE TITLE
Simple Linear Regression

### ISSUE THREAD

**Issue by rithurajnambiar17** [Math-behind-AI/ScratchAI#1]
**Name**
Simple Linear Regression

**Packages used**
`Pandas` : 1.2.4
`Numpy` : 1.19.5

**Brief  explanation**
Creating a Simple Linear Regression model, that could have the best fit line among the given dataset and thus make predictions

**Comment by mayureshagashe2105** [comment]
Sure, you can submit your model!!!
Make a sub directory under `traditional_ML_algorithms` and include following:
> 1. `model.py` (Implementation of your algo/model)
> 2.  `tutorial.ipynb` (Working instance of your model/algo)
> 3. `README.md` (Description for your model/algo)

- Before creating PR please fill necessary information in this issue.
