### ISSUE TITLE
K-Means

### ISSUE THREAD

**Issue by AAnirudh07** [Math-behind-AI/ScratchAI#10]
**Name**
K-Means

**Packages used**
`pandas` - 1.3.4
`numpy` - 1.21.4

**Brief  explanation**
Unsupervised learning algorithm to group data points into k different clusters.
#### Input 
Set of data points 
#### Working 
1. Initialize cluster centers
2. Until the cluster centers converge:
        Assign data points to nearest cluster center
        Update cluster centers
#### Output
Number of clusters and cluster label for each data point.

**Comment by HemanthSai7** [comment]
Hi, @AAnirudh07 Thanks for showing interest in contributing to ScratchAI. You can work on your algorithm and feel free to reach out to us if you face any difficulty. Please open a PR once you are done with your algorithm.
Thank you
