### ISSUE TITLE
Add Word Embeddings

### ISSUE THREAD

**Issue by mayureshagashe2105** [Math-behind-AI/ScratchAI#3]
**Name**
Word Embeddings (Word2Vec)

**Packages used**
tensorflow==2.5.0
numpy ==1.19.5
pandas==1.2.4

**Brief  explanation**
Word embedding is used to extract semantic relations between different words by plotting them in a vector space.

**Comment by r-o-n-i-t** [comment]
Hi there
I am a participant in Hacktober 2k22. I want to contribute to this issue.
Please assign me this issue.
Thank you
@mayureshagashe2105

**Comment by mayureshagashe2105** [comment]
Hello @r-o-n-i-t, hope you are doing great!
Thank you for your interest in ScreacthAI. Assigning this issue to you. Feel free to reach out if you have any queries. Once you are done with the implementation make a PR.

**Comment by HemanthSai7** [comment]
I'll work on this issue.
